class UserException(Exception):
    pass


class UserAlreadyExistsException(UserException):
    pass
